fix: return empty list when get_assigned_certificates given no tls relation
canonical/tls-certificates-interface pull request #119
Opened 2024-02-21 23:35 UTC by gruyaume

# Description

In cases where charms call `get_assigned_certificates()` and the tls relation was not created, the method would raise a Runtime error. Instead of that we now return an empty list since really, no cert has been assigned.

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2024-02-22 05:58 UTC, saltiyazan approved these changes

2024-02-22 09:07 UTC, Kayra1 requested changes
Quick question about consistent responses with public methods.

2024-02-22 18:43 UTC, gruyaume commented on lib/charms/tls_certificates_interface/v3/tls_certificates.py
>          for requirer_csr in self.get_certificate_signing_requests(fulfilled_only=True):
Good point, I agree, I moved this to the `get_requirer_csrs` and added tests to make sure the same behavior applies to all public `gets`.

2024-02-23 06:39 UTC, Kayra1 approved these changes

2024-02-23 12:51 UTC, merged