fix: Uses relation ID when available
canonical/tls-certificates-interface pull request #87
Opened 2023-11-02 12:50 UTC by gruyaume

# Description

Uses relation ID when available and improves method name.

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-11-04 14:35 UTC, ghislainbourgeois requested changes
Looks good, small comment.

2023-11-04 14:35 UTC, ghislainbourgeois commented on lib/charms/tls_certificates_interface/v2/tls_certificates.py
> +            relation_id (int): Relation ID
```suggestion
            relation_id (Optional[int]): Relation ID
```

2023-11-05 11:21 UTC, gruyaume commented on lib/charms/tls_certificates_interface/v2/tls_certificates.py
> +            relation_id (int): Relation ID
Done

2023-11-14 20:56 UTC, ghislainbourgeois approved these changes

2023-11-14 21:12 UTC, merged